In [1]:
import numpy as np


In [2]:
b=np.random.random((3,3))

In [3]:
c=np.random.random((3,3))

In [4]:
b

array([[0.56633468, 0.7169759 , 0.34501008],
       [0.70951646, 0.78266704, 0.61532046],
       [0.1691829 , 0.86767484, 0.9861217 ]])

In [5]:
c

array([[0.86084985, 0.75562608, 0.74892395],
       [0.54169487, 0.70486216, 0.52322622],
       [0.8294296 , 0.58046381, 0.42815708]])

In [6]:
b + c

array([[1.42718453, 1.47260197, 1.09393403],
       [1.25121133, 1.4875292 , 1.13854668],
       [0.9986125 , 1.44813865, 1.41427878]])

In [7]:
b -c

array([[-0.29451517, -0.03865018, -0.40391388],
       [ 0.1678216 ,  0.07780488,  0.09209424],
       [-0.6602467 ,  0.28721103,  0.55796462]])

In [8]:
b*c

array([[0.48752912, 0.54176568, 0.25838631],
       [0.38434143, 0.55167238, 0.3219518 ],
       [0.14032531, 0.50365384, 0.42221499]])

In [9]:
b/c

array([[0.65787858, 0.94885013, 0.46067438],
       [1.30980836, 1.11038311, 1.17601228],
       [0.203975  , 1.49479576, 2.30317737]])

In [10]:
b%c

array([[0.56633468, 0.7169759 , 0.34501008],
       [0.1678216 , 0.07780488, 0.09209424],
       [0.1691829 , 0.28721103, 0.12980754]])

In [11]:
1/c

array([[1.16164276, 1.32340589, 1.33524906],
       [1.84605774, 1.41871709, 1.9112192 ],
       [1.20564783, 1.72276029, 2.33559141]])

In [12]:
2/b

array([[ 3.53148073,  2.78949405,  5.79693215],
       [ 2.81882113,  2.55536505,  3.25033885],
       [11.82152541,  2.30501094,  2.02814724]])

In [13]:
b += c #b=b+c

In [14]:
b

array([[1.42718453, 1.47260197, 1.09393403],
       [1.25121133, 1.4875292 , 1.13854668],
       [0.9986125 , 1.44813865, 1.41427878]])

In [15]:
 b**2

array([[2.03685568, 2.16855657, 1.19669166],
       [1.56552979, 2.21274313, 1.29628855],
       [0.99722693, 2.09710555, 2.00018447]])

In [16]:
0.52522541 *0.52522541

0.2758617313096681

In [17]:
1.45346678 * 1.45346678

2.1125656805635686