In [1]:
import numpy as np

In [2]:
np.random.randint(12)

11

In [3]:
arr1=np.random.randn(12)

In [4]:
arr1

array([ 0.75437263, -0.30566148,  0.96717203,  0.88772548,  0.07128481,
        0.18646117, -0.0663356 , -0.55695265,  0.33905565,  2.33277039,
       -0.70435165,  0.87111555])

In [5]:
np.sqrt(arr1)

C:\Users\yogar\AppData\Local\Temp\ipykernel_20656\3299852782.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([0.86854628,        nan, 0.98344905, 0.94219185, 0.26699215,
       0.4318115 ,        nan,        nan, 0.58228486, 1.52734095,
              nan, 0.93333571])

In [6]:
np.exp(arr1)

array([ 2.12627715,  0.73663594,  2.63049497,  2.42959719,  1.07388703,
        1.20497783,  0.93581675,  0.57295239,  1.40362146, 10.30645493,
        0.49442903,  2.38957505])

In [7]:
arr2=np.random.randn(12)

In [8]:
arr2

array([-0.43005225, -0.56106588,  0.69560972, -0.7228123 ,  0.78097951,
       -0.71091097, -1.32180033, -1.02831247, -1.49051113,  1.6039648 ,
        1.02832993,  0.09273232])

In [10]:
np.add(arr1,arr2)

array([ 0.32432038, -0.86672736,  1.66278175,  0.16491318,  0.85226431,
       -0.5244498 , -1.38813593, -1.58526512, -1.15145548,  3.93673519,
        0.32397828,  0.96384787])

In [13]:
np.minimum(arr1,arr2)

array([-0.43005225, -0.56106588,  0.69560972, -0.7228123 ,  0.07128481,
       -0.71091097, -1.32180033, -1.02831247, -1.49051113,  1.6039648 ,
       -0.70435165,  0.09273232])

In [14]:
np.maximum(arr1,arr2)

array([ 0.75437263, -0.30566148,  0.96717203,  0.88772548,  0.78097951,
        0.18646117, -0.0663356 , -0.55695265,  0.33905565,  2.33277039,
        1.02832993,  0.87111555])