In [1]:
import numpy as np

In [5]:
arr=np.array([[34,456,78,987,23,34],[10,20,30,40,50,60],[1,2,3,4,5,6]])

In [8]:
arr.transpose()

array([[ 34,  10,   1],
       [456,  20,   2],
       [ 78,  30,   3],
       [987,  40,   4],
       [ 23,  50,   5],
       [ 34,  60,   6]])

In [16]:
arr=np.arange(40).reshape(4,10)

In [17]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [18]:
arr=np.arange(40).reshape(4,5,2)

In [19]:
arr.transpose()

array([[[ 0, 10, 20, 30],
        [ 2, 12, 22, 32],
        [ 4, 14, 24, 34],
        [ 6, 16, 26, 36],
        [ 8, 18, 28, 38]],

       [[ 1, 11, 21, 31],
        [ 3, 13, 23, 33],
        [ 5, 15, 25, 35],
        [ 7, 17, 27, 37],
        [ 9, 19, 29, 39]]])

In [20]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [21]:
arr.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39]]])