In [1]:
import numpy as np


In [2]:
arr=np.random.randn(4,4)

In [3]:
arr

array([[ 0.66845956, -0.54120402, -1.90028635, -0.32967023],
       [ 1.10163052,  0.65172479, -2.37669249, -1.22420385],
       [ 0.81262106, -0.71276641,  0.35326979, -2.53548508],
       [-1.38026031, -0.11730294, -0.53465843,  0.68748617]])

In [4]:
arr.sum()

-7.377338203890348

In [5]:
arr.mean()

-0.46108363774314676

In [6]:
arr.var()

1.2651791535314403

In [7]:
arr.std()

1.124801828559787

In [8]:
np.where(arr<0)


(array([0, 0, 0, 1, 1, 2, 2, 3, 3, 3], dtype=int64),
 array([1, 2, 3, 2, 3, 1, 3, 0, 1, 2], dtype=int64))

In [9]:
np.where(arr<0,0,arr)

array([[0.66845956, 0.        , 0.        , 0.        ],
       [1.10163052, 0.65172479, 0.        , 0.        ],
       [0.81262106, 0.        , 0.35326979, 0.        ],
       [0.        , 0.        , 0.        , 0.68748617]])

In [10]:
arr.sort()

In [11]:
arr

array([[-1.90028635, -0.54120402, -0.32967023,  0.66845956],
       [-2.37669249, -1.22420385,  0.65172479,  1.10163052],
       [-2.53548508, -0.71276641,  0.35326979,  0.81262106],
       [-1.38026031, -0.53465843, -0.11730294,  0.68748617]])